services:
  server:
    build:
      dockerfile: apps/server/Dockerfile
      context: .
    ports:
      - 8000:8000
    environment:
      MONGO_URI: mongodb://mongodb:27017/monorepo?directConnection=true
      # SQLITE_URL: file://./.sqlite.db

      # postgres:
      #   container_name: postgres
      #   image: postgres:latest
      #   hostname: postgres
      #   ports:
      #     - 5432:5432
      #   volumes:
      #     - postgres_data:/var/lib/postgresql/data
      #   environment:
      #     POSTGRES_USER: mono
      #     POSTGRES_PASSWORD: repo
      #     POSTGRES_DB: dev

  mongodb:
    container_name: mongo
    image: mongo:latest
    hostname: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongo-setup:
    container_name: mongo_setup
    image: mongo:latest
    depends_on:
      - mongodb
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]

volumes:
  mongo_data: {}
  postgres_data: {}
